### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by desertnaut** [jxbz/fromage#3]
Kudos for the great work!

The 2nd link of the related work in the Acknowledgements section:  

> - See [here](https://arxiv.org/abs/1708.03888) and [here](https://people.eecs.berkeley.edu/~youyang/publications/batch32k.pdf) for closely related work by Yang You, Igor Gitman and Boris Ginsburg.

is broken; I trust you meant to link to https://arxiv.org/abs/1904.00962

**Comment by jxbz** [comment]
Thanks for the pointer---I think Yang You's old Berkeley homepage was shut down. I'll update those links!
