### ISSUE TITLE
Experiments on Convolutional Neural Nets

### ISSUE THREAD

**Issue by okbalefthanded** [jxbz/fromage#4]
Hi!
Thanks for providing accompanying paper code, I was wondering if you have experimented with Fromage on CNNs?

**Comment by jxbz** [comment]
Hi! Thanks for your question.

We have! The Imagenet and Cifar-10 classification experiments used resnet-50 and resnet-18 respectively. Both are CNNs.

**Comment by okbalefthanded** [comment]
Thanks for the clarification, I'll check the experiments thoroughly and work with them.
